# Generated by Django 3.1.2 on 2020-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match_List', '0003_match_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_summary',
            name='gun_banned_player1',
            field=models.CharField(choices=[('AK', 'Ak'), ('AWP', 'AWP'), ('AUG', 'AUG'), ('GAY_GUN', 'SCAR'), ('Others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='match_summary',
            name='gun_banned_player2',
            field=models.CharField(choices=[('AK', 'Ak'), ('AWP', 'AWP'), ('AUG', 'AUG'), ('GAY_GUN', 'SCAR'), ('Others', 'Others')], max_length=15),
        ),
    ]
